name            = "roangela-gclid"
main            = "index.js"
compatibility_date = "2024-09-23"

# KV namespace para armazenar os leads com GCLID
# Crie com: npx wrangler kv namespace create "GCLID_KV"
# e cole o id retornado abaixo
[[kv_namespaces]]
binding = "GCLID_KV"
id      = "9979552f4a1c4113a1e868353719a103"

# Variáveis de ambiente
[vars]
ALLOWED_ORIGIN   = "https://psicorosangelarocha.com"
# URL do Google Apps Script Web App (preencher após deploy do Apps Script)
APPS_SCRIPT_URL  = "https://script.google.com/macros/s/AKfycbw2mCZGodw2AtzBfIBjnAtT7wfxWJwb7PCCtmq00Lbk4WDjHk4-iEiRkBRYjrQiWdsnDQ/exec"
